# 설치 & 확인

## pip install

In [1]:
!pip install ultralytics==8.0.196 --quiet
!pip install roboflow --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 631.1/631.1 kB 13.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 71.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 87.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 50.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 10.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 62.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.1/83.1 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 

# 런타임 환경 확인

## Import

In [2]:
from IPython import display
from IPython.display import Image
from roboflow import Roboflow
import ultralytics
from ultralytics import YOLO
import os

## Version

In [3]:
display.clear_output()
ultralytics.checks()

HOME = os.getcwd()
print(HOME)

Ultralytics YOLOv8.0.196 🚀 Python-3.11.11 torch-2.5.1+cu124 CUDA:0 (Tesla T4, 15095MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 33.2/112.6 GB disk)


/content


# 간이 테스트

In [4]:
#!yolo task=detect mode=predict model=yolov8n.pt conf=0.25 source='https://media.roboflow.com/notebooks/examples/dog.jpeg' save=True
#Image(filename='runs/detect/predict/dog.jpeg', height=600)

In [5]:
#!mkdir {HOME}/datasets
#%cd {HOME}/datasets

# Model Run

In [6]:
# api_key는 계정마다 다름
rf = Roboflow(api_key="wNo4QrXGVHMuGz8nVoBq")
project = rf.workspace("yolov8n-shyng").project("one-q")
version = project.version(1)
dataset = version.download("yolov8")

loading Roboflow workspace...
loading Roboflow project...



Extracting Dataset Version Zip to ONE-Q-1 in yolov8:: 100%|██████████| 3030/3030 [00:00<00:00, 4072.97it/s]


In [ ]:
"""
### ----- CLI 방식 ----- ###
# Train
# train 이후 나온 weight에 이어서 재학습 시키려면 yolov8n.pt를 best.pt로 바꾸면 되지 않을까 싶음
!yolo task=detect mode=train model=yolov8n.pt data={dataset.location}/data.yaml epochs=30 imgsz=640 plots=True

# Predict
!yolo task=detect mode=predict model=/content/runs/detect/train/weights/best.pt conf=0.7 source={dataset.location}/test/images save=True
"""

In [7]:
### ----- Code 방식 ----- ###
# Train
model = YOLO("yolov8n.pt")
model.info()
model.train(data=f"{dataset.location}/data.yaml", epochs=30, imgsz=640)  # "./datasets/ONE-Q-1/data.yaml"

100%|██████████| 6.23M/6.23M [00:00<00:00, 113MB/s]
You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
YOLOv8n summary: 225 layers, 3157200 parameters, 0 gradients, 8.9 GFLOPs
New https://pypi.or

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x7b1d13f57b50>
fitness: 0.8727297746060612
keys: ['metrics/precision(B)', 'metrics/recall(B)', 'metrics/mAP50(B)', 'metrics/mAP50-95(B)']
maps: array([    0.85552,     0.86277])
names: {0: 'Rear-Side Car', 1: 'Side-Side Car'}
plot: True
results_dict: {'metrics/precision(B)': 0.9964846297361457, 'metrics/recall(B)': 1.0, 'metrics/mAP50(B)': 0.995, 'metrics/mAP50-95(B)': 0.8591441940067346, 'fitness': 0.8727297746060612}
save_dir: PosixPath('runs/detect/train')
speed: {'preprocess': 0.23142083898767246, 'inference': 2.455599896319501, 'loss': 0.000582112894429789, 'postprocess': 1.9091104532217051}

In [14]:
# Test(predict)
model = YOLO("./runs/detect/train/weights/best.pt")
testImgDir = (f"{dataset.location}/test/images") # "./ONE-Q-1/test/images"

print(testImgDir)
for img in os.listdir(testImgDir):
  imgName = f"{testImgDir}/{img}"
  #print(imgName)
  results = model.predict(source=imgName, save=True)
  print(results[0].boxes.xyxy, results[0].boxes.xyxyn)


image 1/1 /content/ONE-Q-1/test/images/IMG_2456_jpg.rf.aefdf9e9fbeef6f38ee880a9a4aef52b.jpg: 640x640 1 Side-Side Car, 9.7ms
Speed: 2.6ms preprocess, 9.7ms inference, 2.8ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4


/content/ONE-Q-1/test/images
tensor([[209.3929, 312.6387, 325.0471, 377.0923]], device='cuda:0') 


image 1/1 /content/ONE-Q-1/test/images/IMG_2161_jpg.rf.1410cd3b67615510ed23e6f3a7429d3c.jpg: 640x640 1 Rear-Side Car, 8.2ms
Speed: 3.2ms preprocess, 8.2ms inference, 2.2ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2192_jpg.rf.5a7147d555d997caa756e2e1d318e84c.jpg: 640x640 1 Rear-Side Car, 9.2ms
Speed: 2.7ms preprocess, 9.2ms inference, 2.2ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2697_jpg.rf.33ad26045ceef3ec97fdc9d8e6a00cd9.jpg: 640x640 1 Side-Side Car, 7.7ms
Speed: 2.6ms preprocess, 7.7ms inference, 2.1ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2117_jpg.rf.818afde35b7a1db43610c0d8bb3128b2.jpg: 640x640 1 Rear-Side Car, 10.7ms
Speed: 2.8ms preprocess, 10.7ms inference, 2.6ms postprocess per image at shape (1, 3, 640, 640)


tensor([[0.3272, 0.4885, 0.5079, 0.5892]], device='cuda:0')
tensor([[266.1475, 289.3024, 367.9430, 382.0964]], device='cuda:0') tensor([[0.4159, 0.4520, 0.5749, 0.5970]], device='cuda:0')
tensor([[510.3773, 320.0257, 640.0000, 429.5943]], device='cuda:0') tensor([[0.7975, 0.5000, 1.0000, 0.6712]], device='cuda:0')
tensor([[536.5342, 373.2285, 639.8870, 443.8339]], device='cuda:0') tensor([[0.8383, 0.5832, 0.9998, 0.6935]], device='cuda:0')
tensor([[411.7986, 231.2410, 640.0000, 435.3103]], device='cuda:0') tensor([[0.6434, 0.3613, 1.0000, 0.6802]], device='cuda:0')
tensor([[550.1877, 364.8870, 639.9614, 447.4935]], device='cuda:0') tensor([[0.8597, 0.5701, 0.9999, 0.6992]], device='cuda:0')
tensor([[488.9350, 370.9969, 639.2852, 464.8199]], device='cuda:0') tensor([[0.7640, 0.5797, 0.9989, 0.7263]], device='cuda:0')


image 1/1 /content/ONE-Q-1/test/images/IMG_2465_jpg.rf.58863efe7488f435bfdbd071ba0bf2f1.jpg: 640x640 1 Side-Side Car, 7.9ms
Speed: 2.6ms preprocess, 7.9ms inference, 2.1ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2308_jpg.rf.b1e43fdd1638ae2ab79dbed3e840d26b.jpg: 640x640 1 Side-Side Car, 12.0ms
Speed: 2.5ms preprocess, 12.0ms inference, 1.9ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2193_jpg.rf.f7ca777878dbc8e7176bd6fbde953a86.jpg: 640x640 1 Rear-Side Car, 7.5ms
Speed: 2.6ms preprocess, 7.5ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2696_jpg.rf.1b4fd988c1473e791a3ea1b055700816.jpg: 640x640 1 Side-Side Car, 7.6ms
Speed: 2.7ms preprocess, 7.6ms inference, 2.2ms postprocess per image at shape (1, 3, 640, 640)
R

tensor([[ 96.7990, 315.5109, 222.3109, 381.8545]], device='cuda:0') tensor([[0.1512, 0.4930, 0.3474, 0.5966]], device='cuda:0')
tensor([[393.0396, 347.9245, 613.3168, 465.0578]], device='cuda:0') tensor([[0.6141, 0.5436, 0.9583, 0.7267]], device='cuda:0')
tensor([[502.3206, 318.2781, 639.9210, 425.2280]], device='cuda:0') tensor([[0.7849, 0.4973, 0.9999, 0.6644]], device='cuda:0')
tensor([[  0.0000, 320.0357, 130.1265, 415.4189]], device='cuda:0') tensor([[0.0000, 0.5001, 0.2033, 0.6491]], device='cuda:0')
tensor([[218.8862, 313.5732, 333.6967, 377.6157]], device='cuda:0') tensor([[0.3420, 0.4900, 0.5214, 0.5900]], device='cuda:0')
tensor([[ 86.0218, 290.1866, 231.9947, 373.4460]], device='cuda:0') tensor([[0.1344, 0.4534, 0.3625, 0.5835]], device='cuda:0')
tensor([[292.1901, 299.2778, 612.9611, 482.8514]], device='cuda:0')


image 1/1 /content/ONE-Q-1/test/images/IMG_2259_jpg.rf.fefc1f431b6cc57b8eed4221640da351.jpg: 640x640 1 Side-Side Car, 8.0ms
Speed: 2.5ms preprocess, 8.0ms inference, 2.1ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2470_jpg.rf.272c15cffca772654c9f508aff65cd84.jpg: 640x640 1 Side-Side Car, 8.0ms
Speed: 2.5ms preprocess, 8.0ms inference, 2.1ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2457_jpg.rf.055f1265b2f5792e8969604caf031f10.jpg: 640x640 1 Side-Side Car, 7.9ms
Speed: 2.5ms preprocess, 7.9ms inference, 2.3ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2468_jpg.rf.28863783dc35a9366ccdfabfd9ae8e32.jpg: 640x640 1 Side-Side Car, 9.0ms
Speed: 2.3ms preprocess, 9.0ms inference, 2.1ms postprocess per image at shape (1, 3, 640, 640)
Re

 tensor([[0.4565, 0.4676, 0.9578, 0.7545]], device='cuda:0')
tensor([[171.0922, 289.4000, 497.3945, 477.6249]], device='cuda:0') tensor([[0.2673, 0.4522, 0.7772, 0.7463]], device='cuda:0')
tensor([[ 47.3748, 304.8665, 180.5643, 375.8355]], device='cuda:0') tensor([[0.0740, 0.4764, 0.2821, 0.5872]], device='cuda:0')
tensor([[212.3635, 309.6711, 326.0030, 374.3488]], device='cuda:0') tensor([[0.3318, 0.4839, 0.5094, 0.5849]], device='cuda:0')
tensor([[ 58.0788, 306.5330, 191.8698, 375.0250]], device='cuda:0') tensor([[0.0907, 0.4790, 0.2998, 0.5860]], device='cuda:0')
tensor([[1.0373e-01, 3.1935e+02, 1.6163e+02, 4.1099e+02]], device='cuda:0') tensor([[1.6208e-04, 4.9899e-01, 2.5255e-01, 6.4218e-01]], device='cuda:0')
tensor([[419.1808, 223.3290, 640.0000, 425.9654]], device='cuda:0') tensor([[0.6550, 0.3490, 1.0000, 0.6656]], device='cuda:0')


Speed: 2.4ms preprocess, 7.8ms inference, 2.3ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2667_jpg.rf.038214792769efcb3ab2620a753adef8.jpg: 640x640 1 Side-Side Car, 8.7ms
Speed: 2.5ms preprocess, 8.7ms inference, 2.2ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2486_jpg.rf.7378aac49e1af5861bc26c4f056416c3.jpg: 640x640 1 Side-Side Car, 8.3ms
Speed: 2.7ms preprocess, 8.3ms inference, 2.1ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2444_jpg.rf.74b6124b6023e90b5a1eebbc0cb51e9a.jpg: 640x640 1 Side-Side Car, 13.5ms
Speed: 2.7ms preprocess, 13.5ms inference, 2.3ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2732_jpg.rf.9507a084059d278abe745edce450cdd

tensor([[105.0277, 322.8180, 227.1279, 385.7001]], device='cuda:0') tensor([[0.1641, 0.5044, 0.3549, 0.6027]], device='cuda:0')
tensor([[226.9656, 267.7675, 358.7352, 347.6687]], device='cuda:0') tensor([[0.3546, 0.4184, 0.5605, 0.5432]], device='cuda:0')
tensor([[554.5182, 357.4289, 640.0000, 436.2349]], device='cuda:0') tensor([[0.8664, 0.5585, 1.0000, 0.6816]], device='cuda:0')
tensor([[388.7769, 319.4027, 507.7540, 383.4643]], device='cuda:0') tensor([[0.6075, 0.4991, 0.7934, 0.5992]], device='cuda:0')
tensor([[2.1098e-01, 2.7403e+02, 1.0660e+02, 3.4210e+02]], device='cuda:0') tensor([[3.2965e-04, 4.2818e-01, 1.6657e-01, 5.3453e-01]], device='cuda:0')
tensor([[223.1503, 313.7101, 334.7001, 379.2121]], device='cuda:0') tensor([[0.3487, 0.4902, 0.5230, 0.5925]], device='cuda:0')
tensor([[131.9616, 262.9716, 243.5851, 359.9824]], device='cuda:0') tensor([[0.2062, 0.4109, 0.3806, 0.5625]], device='cuda:0')


image 1/1 /content/ONE-Q-1/test/images/IMG_2442_jpg.rf.ed774aff6ad1128bedd4004a06c82557.jpg: 640x640 1 Side-Side Car, 9.9ms
Speed: 2.4ms preprocess, 9.9ms inference, 2.1ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2715_jpg.rf.44dc0e2dfdc06f77c3001248361074f0.jpg: 640x640 1 Side-Side Car, 8.2ms
Speed: 2.8ms preprocess, 8.2ms inference, 2.1ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2692_jpg.rf.ddbc1ad64ec0b7ee621b4fcbdc57d380.jpg: 640x640 1 Side-Side Car, 10.7ms
Speed: 2.5ms preprocess, 10.7ms inference, 2.2ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2448_jpg.rf.aa38f9d0b9a57e5140a0793e61463a83.jpg: 640x640 1 Side-Side Car, 11.1ms
Speed: 2.9ms preprocess, 11.1ms inference, 2.3ms postprocess per image at shape (1, 3, 640, 640)

tensor([[408.9394, 322.7443, 527.4858, 386.9628]], device='cuda:0') tensor([[0.6390, 0.5043, 0.8242, 0.6046]], device='cuda:0')
tensor([[254.6123, 312.9494, 349.5579, 368.8031]], device='cuda:0') tensor([[0.3978, 0.4890, 0.5462, 0.5763]], device='cuda:0')
tensor([[  0.0000, 319.8101, 153.1270, 410.5982]], device='cuda:0') tensor([[0.0000, 0.4997, 0.2393, 0.6416]], device='cuda:0')
tensor([[318.7468, 323.6638, 431.3208, 384.8663]], device='cuda:0') tensor([[0.4980, 0.5057, 0.6739, 0.6014]], device='cuda:0')
tensor([[124.2332, 264.7823, 237.7612, 360.2715]], device='cuda:0') tensor([[0.1941, 0.4137, 0.3715, 0.5629]], device='cuda:0')
tensor([[366.8008, 328.8338, 466.9945, 390.0992]], device='cuda:0') tensor([[0.5731, 0.5138, 0.7297, 0.6095]], device='cuda:0')


image 1/1 /content/ONE-Q-1/test/images/IMG_2451_jpg.rf.832ace4043ab5e5ad781252541540f30.jpg: 640x640 1 Side-Side Car, 12.8ms
Speed: 2.6ms preprocess, 12.8ms inference, 2.4ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2685_jpg.rf.676a207c0108ca85e17214f6655e6091.jpg: 640x640 1 Side-Side Car, 9.6ms
Speed: 2.9ms preprocess, 9.6ms inference, 2.3ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2172_jpg.rf.49bcb32a1d69ef0b4f77cf6ce54bf8e6.jpg: 640x640 1 Rear-Side Car, 9.4ms
Speed: 2.9ms preprocess, 9.4ms inference, 2.3ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2437_jpg.rf.fea399306e5cf0b83a8117e21488091b.jpg: 640x640 1 Side-Side Car, 10.3ms
Speed: 2.5ms preprocess, 10.3ms inference, 2.4ms postprocess per image at shape (1, 3, 640, 640)

tensor([[282.4835, 323.0823, 393.2871, 384.1455]], device='cuda:0') tensor([[0.4414, 0.5048, 0.6145, 0.6002]], device='cuda:0')
tensor([[ 37.4058, 304.5811, 192.1382, 392.7479]], device='cuda:0') tensor([[0.0584, 0.4759, 0.3002, 0.6137]], device='cuda:0')
tensor([[141.2486, 263.4176, 252.9342, 359.4562]], device='cuda:0') tensor([[0.2207, 0.4116, 0.3952, 0.5617]], device='cuda:0')
tensor([[488.7506, 338.9528, 619.2134, 411.0210]], device='cuda:0') tensor([[0.7637, 0.5296, 0.9675, 0.6422]], device='cuda:0')
tensor([[497.5008, 347.2946, 631.1764, 418.3049]], device='cuda:0') tensor([[0.7773, 0.5426, 0.9862, 0.6536]], device='cuda:0')
tensor([[ 88.8245, 250.6062, 358.5421, 470.5928]], device='cuda:0') tensor([[0.1388, 0.3916, 0.5602, 0.7353]], device='cuda:0')


image 1/1 /content/ONE-Q-1/test/images/IMG_2480_jpg.rf.df19a31958cc812f9025f4c166587a57.jpg: 640x640 1 Side-Side Car, 11.0ms
Speed: 2.7ms preprocess, 11.0ms inference, 2.5ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2453_jpg.rf.cb90bcefabb5f10c3ebd84944ab71db2.jpg: 640x640 1 Side-Side Car, 14.1ms
Speed: 4.8ms preprocess, 14.1ms inference, 3.3ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2450_jpg.rf.c68c79f74d0735ea5a65e15bd99f72c4.jpg: 640x640 1 Side-Side Car, 14.0ms
Speed: 4.2ms preprocess, 14.0ms inference, 3.8ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2164_jpg.rf.90cf0f29ae765909a49c536244811f98.jpg: 640x640 1 Rear-Side Car, 14.0ms
Speed: 3.3ms preprocess, 14.0ms inference, 3.6ms postprocess per image at shape (1, 3, 640,


tensor([[  0.0000, 343.2671, 100.4514, 434.0999]], device='cuda:0') tensor([[0.0000, 0.5364, 0.1570, 0.6783]], device='cuda:0')
tensor([[239.7052, 312.5656, 351.3419, 376.3804]], device='cuda:0') tensor([[0.3745, 0.4884, 0.5490, 0.5881]], device='cuda:0')
tensor([[294.1041, 324.7484, 406.0354, 385.5235]], device='cuda:0') tensor([[0.4595, 0.5074, 0.6344, 0.6024]], device='cuda:0')
tensor([[214.0051, 274.0137, 318.8015, 368.6421]], device='cuda:0') tensor([[0.3344, 0.4281, 0.4981, 0.5760]], device='cuda:0')


image 1/1 /content/ONE-Q-1/test/images/IMG_2469_jpg.rf.d692308ed07e56b11a9f0416b883906f.jpg: 640x640 1 Side-Side Car, 15.1ms
Speed: 5.2ms preprocess, 15.1ms inference, 3.6ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2440_jpg.rf.7f5ba1a73c400e20479938f8db73e6e8.jpg: 640x640 1 Side-Side Car, 13.6ms
Speed: 4.5ms preprocess, 13.6ms inference, 2.7ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2190_jpg.rf.d89fb2b9a7de3687950c4572702cfd31.jpg: 640x640 1 Rear-Side Car, 16.4ms
Speed: 4.2ms preprocess, 16.4ms inference, 4.7ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2707_jpg.rf.f0722d9f5db873daff0b62f5ce881459.jpg: 640x640 1 Side-Side Car, 15.9ms
Speed: 3.4ms preprocess, 15.9ms inference, 2.6ms postprocess per image at shape (1, 3, 640, 

tensor([[ 50.7563, 306.0466, 185.9821, 377.2455]], device='cuda:0') tensor([[0.0793, 0.4782, 0.2906, 0.5894]], device='cuda:0')
tensor([[441.1817, 328.9128, 566.3774, 396.4136]], device='cuda:0') tensor([[0.6893, 0.5139, 0.8850, 0.6194]], device='cuda:0')
tensor([[  8.5484, 326.0563, 143.2520, 428.8232]], device='cuda:0') tensor([[0.0134, 0.5095, 0.2238, 0.6700]], device='cuda:0')
tensor([[398.9711, 336.1216, 504.5151, 401.6804]], device='cuda:0') tensor([[0.6234, 0.5252, 0.7883, 0.6276]], device='cuda:0')
tensor([[ 96.9526, 321.2991, 220.8409, 384.8672]], device='cuda:0') tensor([[0.1515, 0.5020, 0.3451, 0.6014]], device='cuda:0')


image 1/1 /content/ONE-Q-1/test/images/IMG_2695_jpg.rf.f69ed6fd73bed41429607eea7e850722.jpg: 640x640 1 Side-Side Car, 16.6ms
Speed: 2.8ms preprocess, 16.6ms inference, 3.7ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2122_jpg.rf.f677c0ded724c5fa6ce79df831776c2b.jpg: 640x640 1 Rear-Side Car, 11.8ms
Speed: 5.0ms preprocess, 11.8ms inference, 2.3ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2664_jpg.rf.3fd544e3705edede6a6c9acfe9d5a5b0.jpg: 640x640 1 Side-Side Car, 17.3ms
Speed: 6.5ms preprocess, 17.3ms inference, 2.6ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2724_jpg.rf.308d560bb14ab8f5b20e9e6a35ed8f57.jpg: 640x640 1 Side-Side Car, 10.9ms
Speed: 3.4ms preprocess, 10.9ms inference, 2.7ms postprocess per image at shape (1, 3, 640, 

tensor([[  0.0000, 322.3901, 134.0246, 416.3273]], device='cuda:0') tensor([[0.0000, 0.5037, 0.2094, 0.6505]], device='cuda:0')
tensor([[332.9927, 270.5361, 605.4974, 477.5771]], device='cuda:0') tensor([[0.5203, 0.4227, 0.9461, 0.7462]], device='cuda:0')
tensor([[222.0376, 279.7508, 350.2800, 360.3460]], device='cuda:0') tensor([[0.3469, 0.4371, 0.5473, 0.5630]], device='cuda:0')
tensor([[ 61.6165, 264.6353, 173.7883, 328.3881]], device='cuda:0') tensor([[0.0963, 0.4135, 0.2715, 0.5131]], device='cuda:0')
tensor([[  5.8659, 315.5114, 147.8583, 394.6057]], device='cuda:0') tensor([[0.0092, 0.4930, 0.2310, 0.6166]], device='cuda:0')


image 1/1 /content/ONE-Q-1/test/images/IMG_2255_jpg.rf.8e8592afe5161310a1395eb5ecdb630f.jpg: 640x640 1 Side-Side Car, 12.3ms
Speed: 2.6ms preprocess, 12.3ms inference, 3.5ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2701_jpg.rf.f669cf7a316c1a21ae3f8d7f7dfe96f1.jpg: 640x640 1 Side-Side Car, 15.4ms
Speed: 2.7ms preprocess, 15.4ms inference, 2.6ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2178_jpg.rf.8f7be1b81ffdf46131bf6cf29949544e.jpg: 640x640 1 Rear-Side Car, 11.8ms
Speed: 2.8ms preprocess, 11.8ms inference, 2.6ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2452_jpg.rf.9c9aeabfc1c89248d7905c7827b222e4.jpg: 640x640 1 Side-Side Car, 21.1ms
Speed: 2.6ms preprocess, 21.1ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 

tensor([[267.1134, 291.0292, 582.8344, 477.0367]], device='cuda:0') tensor([[0.4174, 0.4547, 0.9107, 0.7454]], device='cuda:0')
tensor([[531.8020, 367.9722, 639.8359, 439.8385]], device='cuda:0') tensor([[0.8309, 0.5750, 0.9997, 0.6872]], device='cuda:0')
tensor([[ 60.5233, 291.4330, 183.7359, 392.3365]], device='cuda:0') tensor([[0.0946, 0.4554, 0.2871, 0.6130]], device='cuda:0')
tensor([[254.9733, 325.0075, 367.7267, 386.4160]], device='cuda:0') tensor([[0.3984, 0.5078, 0.5746, 0.6038]], device='cuda:0')
tensor([[542.9911, 353.2094, 640.0000, 435.1460]], device='cuda:0') tensor([[0.8484, 0.5519, 1.0000, 0.6799]], device='cuda:0')


Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2449_jpg.rf.d1328e03fbf62a1428d6d898b125c58c.jpg: 640x640 1 Side-Side Car, 10.0ms
Speed: 2.4ms preprocess, 10.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2460_jpg.rf.4a5bf93f25819234ba93eb30da829b3a.jpg: 640x640 1 Side-Side Car, 11.1ms
Speed: 2.4ms preprocess, 11.1ms inference, 2.7ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2471_jpg.rf.65fcc52486ef66ad2944ad5c5fcf5ff9.jpg: 640x640 1 Side-Side Car, 9.3ms
Speed: 2.6ms preprocess, 9.3ms inference, 2.5ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2097_jpg.rf.9112e1188a9e4824adbcaa37b164a659.jpg: 640x640 1 Rear-Side Car, 14.5ms
Speed: 4.7ms preprocess, 14.5ms inference, 3.0ms postpr

tensor([[  0.0000, 345.5598, 100.3961, 431.4575]], device='cuda:0') tensor([[0.0000, 0.5399, 0.1569, 0.6742]], device='cuda:0')
tensor([[300.0035, 321.8588, 412.2518, 382.1699]], device='cuda:0') tensor([[0.4688, 0.5029, 0.6441, 0.5971]], device='cuda:0')
tensor([[144.5793, 322.9384, 264.1520, 386.9963]], device='cuda:0') tensor([[0.2259, 0.5046, 0.4127, 0.6047]], device='cuda:0')
tensor([[ 24.4660, 303.1183, 162.7704, 376.4228]], device='cuda:0') tensor([[0.0382, 0.4736, 0.2543, 0.5882]], device='cuda:0')
tensor([[321.3915, 254.2798, 382.6182, 304.5081]], device='cuda:0') tensor([[0.5022, 0.3973, 0.5978, 0.4758]], device='cuda:0')
tensor([[357.1503, 314.8096, 466.2673, 415.1672]], device='cuda:0') tensor([[0.5580, 0.4919, 0.7285, 0.6487]], device='cuda:0')


image 1/1 /content/ONE-Q-1/test/images/IMG_2459_jpg.rf.81daea62db5b96c4bb75f4d3ed154531.jpg: 640x640 1 Side-Side Car, 14.6ms
Speed: 4.5ms preprocess, 14.6ms inference, 1.9ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2721_jpg.rf.fa4f3844c79b2350c734befc00b8e79e.jpg: 640x640 1 Side-Side Car, 9.9ms
Speed: 2.8ms preprocess, 9.9ms inference, 2.3ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2467_jpg.rf.73787bce9744ec22828b258754644b1e.jpg: 640x640 1 Side-Side Car, 11.5ms
Speed: 2.7ms preprocess, 11.5ms inference, 2.6ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2198_jpg.rf.749753f86a2432fc68d192d704c593b7.jpg: 640x640 1 Rear-Side Car, 9.9ms
Speed: 2.4ms preprocess, 9.9ms inference, 2.5ms postprocess per image at shape (1, 3, 640, 640)

tensor([[213.2464, 324.9033, 327.1712, 390.7338]], device='cuda:0') tensor([[0.3332, 0.5077, 0.5112, 0.6105]], device='cuda:0')
tensor([[ 88.9130, 280.2081, 200.8085, 345.3384]], device='cuda:0') tensor([[0.1389, 0.4378, 0.3138, 0.5396]], device='cuda:0')
tensor([[ 58.4187, 306.7461, 192.1424, 375.7931]], device='cuda:0') tensor([[0.0913, 0.4793, 0.3002, 0.5872]], device='cuda:0')
tensor([[532.1067, 307.7556, 639.9253, 408.9022]], device='cuda:0') tensor([[0.8314, 0.4809, 0.9999, 0.6389]], device='cuda:0')
tensor([[536.0267, 373.0266, 639.8805, 443.7717]], device='cuda:0') tensor([[0.8375, 0.5829, 0.9998, 0.6934]], device='cuda:0')
tensor([[401.6978, 314.1886, 519.5593, 379.5908]], device='cuda:0') tensor([[0.6277, 0.4909, 0.8118, 0.5931]], device='cuda:0')



image 1/1 /content/ONE-Q-1/test/images/IMG_2156_jpg.rf.ea963303ad817c0afa6cf96674eebe12.jpg: 640x640 1 Rear-Side Car, 12.0ms
Speed: 2.5ms preprocess, 12.0ms inference, 2.8ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2464_jpg.rf.5ada4efd38734c472424c669398e4658.jpg: 640x640 1 Side-Side Car, 11.4ms
Speed: 2.7ms preprocess, 11.4ms inference, 3.0ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2439_jpg.rf.3f0c3811c01a9f4fe383520ac7487a8a.jpg: 640x640 1 Side-Side Car, 11.3ms
Speed: 2.6ms preprocess, 11.3ms inference, 2.8ms postprocess per image at shape (1, 3, 640, 640)
Results saved to runs/detect/predict4

image 1/1 /content/ONE-Q-1/test/images/IMG_2479_jpg.rf.6130085f2c814a54d510324e7969dc55.jpg: 640x640 1 Side-Side Car, 11.9ms
Speed: 2.5ms preprocess, 11.9ms inference, 1.9ms postprocess per image at shape (1, 3, 640,

tensor([[294.4409, 307.3523, 390.9099, 362.5840]], device='cuda:0') tensor([[0.4601, 0.4802, 0.6108, 0.5665]], device='cuda:0')
tensor([[332.7789, 328.8412, 436.3965, 428.8747]], device='cuda:0') tensor([[0.5200, 0.5138, 0.6819, 0.6701]], device='cuda:0')
tensor([[ 91.0448, 317.3845, 216.8578, 383.5588]], device='cuda:0') tensor([[0.1423, 0.4959, 0.3388, 0.5993]], device='cuda:0')
tensor([[461.8644, 332.5467, 586.8721, 401.2894]], device='cuda:0') tensor([[0.7217, 0.5196, 0.9170, 0.6270]], device='cuda:0')
tensor([[  0.0000, 343.8544,  98.6722, 435.3816]], device='cuda:0') tensor([[0.0000, 0.5373, 0.1542, 0.6803]], device='cuda:0')
tensor([[2.5940e-03, 3.0491e+02, 1.1240e+02, 4.0283e+02]], device='cuda:0') tensor([[4.0531e-06, 4.7643e-01, 1.7562e-01, 6.2942e-01]], device='cuda:0')
tensor([[460.9243, 323.6203, 640.0000, 448.6697]], device='cuda:0') tensor([[0.7202, 0.5057, 1.0000, 0.7010]], device='cuda:0')


# 코드 방식 train(현재 실행 x)

In [ ]:
"""
result = model('runs/detect/predict/dog.jpeg')

# Process results list
for result in results:
    boxes = result.boxes  # Boxes object for bounding box outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs
    obb = result.obb  # Oriented boxes object for OBB outputs
    result.show()  # display to screen
    result.save(filename="result.jpg")  # save to disk
"""

'\nresult = model(\'runs/detect/predict/dog.jpeg\')\n\n# Process results list\nfor result in results:\n    boxes = result.boxes  # Boxes object for bounding box outputs\n    masks = result.masks  # Masks object for segmentation masks outputs\n    keypoints = result.keypoints  # Keypoints object for pose outputs\n    probs = result.probs  # Probs object for classification outputs\n    obb = result.obb  # Oriented boxes object for OBB outputs\n    result.show()  # display to screen\n    result.save(filename="result.jpg")  # save to disk\n'

In [ ]:
"""
import glob

# path & slicing 수정 필요
for image_path in glob.glob('/content/runs/detect/predict4/*.jpg')[:5]:
  display(Image(filename=image_path, width=640))
  print("\n")
"""

'\nimport glob\n\n# path & slicing 수정 필요\nfor image_path in glob.glob(\'/content/runs/detect/predict4/*.jpg\')[:5]:\n  display(Image(filename=image_path, width=640))\n  print("\n")\n'

# 참고 자료

https://autoever-oneq.atlassian.net/wiki/spaces/ADP/pages/12124230/YOLO